import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "@/components/shared/navbar1";
import SectionContainer from "@/utils/SectionContainer";
import { ThemeProvider } from "@/provider/themeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "🚀MediStore",
  description: "Generated by create next app",
};

// import { betterAuth } from "better-auth";
// import { headers } from "next/headers";
// export const auth = betterAuth({
//     baseURL: "https://medi-store-backend-ashy.vercel.app",
// })
// // calling get session on the server
// const sessionData=await auth.api.getSession({
//     headers: await headers() // some endpoints might require headers
// })

// console.log("SessionData :",sessionData)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning >
      <body
      //   className={`${geistSans.variable} ${geistMono.variable} antialiased`
      // }
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >

          <SectionContainer className="">
            <Navbar1></Navbar1>
            {children}
          </SectionContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
